import type { AlgorithmInfo } from '../types';

export const ALGORITHMS: AlgorithmInfo[] = [
  {
    id: 'bubble',
    name: 'Bubble Sort',
    description: 'Repeatedly compares adjacent elements and swaps them if in wrong order. Simplest sorting algorithm.',
    bestCase: 'O(n)',
    averageCase: 'O(n²)',
    worstCase: 'O(n²)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    color: 'text-blue-500',
    bgColor: 'bg-blue-500',
  },
  {
    id: 'selection',
    name: 'Selection Sort',
    description: 'Finds the minimum element and places it at the beginning. Performs at most n-1 swaps.',
    bestCase: 'O(n²)',
    averageCase: 'O(n²)',
    worstCase: 'O(n²)',
    spaceComplexity: 'O(1)',
    stable: false,
    inPlace: true,
    color: 'text-orange-500',
    bgColor: 'bg-orange-500',
  },
  {
    id: 'insertion',
    name: 'Insertion Sort',
    description: 'Builds a sorted list one element at a time by inserting each element into its correct position.',
    bestCase: 'O(n)',
    averageCase: 'O(n²)',
    worstCase: 'O(n²)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    color: 'text-green-500',
    bgColor: 'bg-green-500',
  },
  {
    id: 'quick',
    name: 'Quick Sort',
    description: 'Divide-and-conquer algorithm that selects a pivot and partitions elements around it recursively.',
    bestCase: 'O(n log n)',
    averageCase: 'O(n log n)',
    worstCase: 'O(n²)',
    spaceComplexity: 'O(log n)',
    stable: false,
    inPlace: true,
    color: 'text-purple-500',
    bgColor: 'bg-purple-500',
  },
  {
    id: 'merge',
    name: 'Merge Sort',
    description: 'Divide-and-conquer algorithm that recursively splits, sorts, and merges sub-arrays.',
    bestCase: 'O(n log n)',
    averageCase: 'O(n log n)',
    worstCase: 'O(n log n)',
    spaceComplexity: 'O(n)',
    stable: true,
    inPlace: false,
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500',
  },
  {
    id: 'heap',
    name: 'Heap Sort',
    description: 'Uses a binary heap data structure to sort elements by repeatedly extracting the maximum.',
    bestCase: 'O(n log n)',
    averageCase: 'O(n log n)',
    worstCase: 'O(n log n)',
    spaceComplexity: 'O(1)',
    stable: false,
    inPlace: true,
    color: 'text-rose-500',
    bgColor: 'bg-rose-500',
  },
  {
    id: 'topological',
    name: 'Topological Sort',
    description: "Kahn's algorithm for linearly ordering vertices of a DAG such that every edge u→v has u before v.",
    bestCase: 'O(V + E)',
    averageCase: 'O(V + E)',
    worstCase: 'O(V + E)',
    spaceComplexity: 'O(V)',
    stable: false,
    inPlace: false,
    color: 'text-amber-500',
    bgColor: 'bg-amber-500',
  },
];

export const ALGORITHM_MAP = Object.fromEntries(ALGORITHMS.map(a => [a.id, a]));

export const BAR_COLORS: Record<string, string> = {
  default:  '#6366f1',
  compare:  '#eab308',
  swap:     '#ef4444',
  set:      '#f97316',
  pivot:    '#a855f7',
  merge:    '#f97316',
  sorted:   '#22c55e',
};

export const API_BASE = 'http://localhost:8080';
